Repository JAYESHBATRA/Virtuo-Learn, pull requests merged in 2024-05, with the labels that each got.

#195 Adding icons . #190
  Pages/3D-Visualizations/index.html
  Pages/3D-Visualizations/style.css
  Pages/About-Us/index.html
  Pages/About-Us/style.css
  Pages/Doubt Engine/index.html
  Pages/Doubt Engine/style.css
  Pages/Quizes/index.html
  Pages/Quizes/style.css
  Pages/Simulation/index.html
  Pages/Simulation/style.css
  Pages/Videos/index.html
  Pages/Videos/style.css
  index.html
  style.css
Labels: title needs formatting

#246 fix: Navbar of the Video player section fixed.
  Pages/Videos/sources/button-1/index.html
  Pages/Videos/sources/button-1/style.css
  Pages/Videos/sources/button-2/index.html
  Pages/Videos/sources/button-2/style.css
  Pages/Videos/sources/button-3/index.html
  Pages/Videos/sources/button-3/style.css
  Pages/Videos/sources/button-4/index.html
  Pages/Videos/sources/button-4/style.css
Labels: gssoc, Level2

#250 navbar made responsive
  Pages/3D-Visualizations/index.html
  Pages/3D-Visualizations/media-queries.css
  Pages/3D-Visualizations/style.css
  Pages/About-Us/index.html
  Pages/About-Us/media-queries.css
  Pages/Doubt Engine/index.html
  Pages/Doubt Engine/media-queries.css
  Pages/Quizes/index.html
  Pages/Quizes/media-queries.css
  Pages/Quizes/style.css
  Pages/Simulation/index.html
  Pages/Simulation/media-queries.css
  Pages/Simulation/style.css
  Pages/Videos/index.html
  Pages/Videos/media-queries.css
  Pages/Videos/style.css
  media-queries.css
  style.css
Labels: title needs formatting, gssoc, level2

#249 feat: Justification Of text
  style.css
Labels: gssoc, level1

#254 feat: Added Hovering Effect to Our Products Section
  index.html
  style.css
Labels: gssoc, level1

#255 I have added testimonials and made it responsive
  Pages/Testimonials/swiper-bundle.min.css
  Pages/Testimonials/swiper-bundle.min.js
  Pages/Testimonials/test-script.js
  Pages/Testimonials/test-style.css
  Pages/Testimonials/testimonials-1.jpg
  Pages/Testimonials/testimonials-2.jpg
  Pages/Testimonials/testimonials-3.jpg
  Pages/Testimonials/testimonials-4.jpg
  index.html
Labels: title needs formatting

#264 fix: Made changes in size of logo
  style.css
Labels: gssoc, level1

#271 fix: Made changes to the font size and favicon size in nav bar
  Pages/3D-Visualizations/style.css
  Pages/About-Us/style.css
  Pages/Doubt Engine/style.css
  Pages/Quizes/style.css
  Pages/Simulation/style.css
  Pages/Videos/style.css
  style.css
Labels: gssoc, level1

#280 fix: heading
  style.css
Labels: gssoc, level1

#290 Improved UI of Bio quiz section.
  Pages/Quizes/tests/button-3/style.css
Labels: title needs formatting, gssoc, level2

#311 Added icons in Footer section
  index.html
Labels: title needs formatting, gssoc, level1

#313 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: title needs formatting, gssoc, level1
