Repository JAYESHBATRA/Virtuo-Learn, pull requests merged in 2024-06, with the labels that each got.

#312 #306 UI improvement in chemistry quiz section.
  Pages/Quizes/tests/button-1/media-queries.css
  Pages/Quizes/tests/button-1/style.css
  Pages/Quizes/tests/button-2/media-queries.css
  Pages/Quizes/tests/button-3/media-queries.css
  Pages/Quizes/tests/button-4/media-queries.css
  Pages/Quizes/tests/button-5/media-queries.css
  Pages/Quizes/tests/button-5/style.css
  Pages/Quizes/tests/button-6/media-queries.css
  Pages/Quizes/tests/button-6/style.css
  Pages/Quizes/tests/button-7/media-queries.css
  Pages/Quizes/tests/button-8/media-queries.css
  Pages/Quizes/tests/button-8/style.css
  Pages/Quizes/tests/button-9/media-queries.css
Labels: Hard, title needs formatting, gssoc

#336 fix: FAQ Page #291 issue solved
  Pages/FAQ/faq.css
  Pages/FAQ/faq.html
  Pages/FAQ/oip1.png
  index.html
Labels: gssoc, level1

#353 Text visible
  Pages/Testimonials/test-style.css
  index.html
  style.css
Labels: title needs formatting, gssoc, level1

#359 Fix: Adding necessary files - Code of Conduct Learn.md and Enhanced Readme
  CODE_OF_CONDUCT.md
  LEARN.md
  README.md
Labels: title needs formatting

#360 Auto commenting feature added for merged prs
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: title needs formatting, gssoc, level1

#362 fix : Made footer responsive.
  index.html
  media-queries.css
Labels: title needs formatting, gssoc, level1
